[workspace]

resolver = "2"
members = [
  "aoc-1",
  "aoc-2",
  "aoc-3",
  "aoc-4",
  "aoc-5",
  "aoc-6",
  "aoc-7",
  "aoc-8",
  "aoc-9",
  "aoc-10",
  "aoc-11",
  "aoc-12",
  "aoc-13",
  "aoc-14",
]
